// ui-angular/src/app/app.component.ts
import { Component, OnInit } from "@angular/core";
import Amplify, { API, Auth, Hub } from "aws-amplify";
import Axios from "axios";
import { User } from "../../../ui-react/src/model/user";
import amplifyConfig from "../../../ui-react/src/config/amplifyConfig";
import { Pet } from "../../../ui-react/src/model/pet";
import { HttpAPIService } from "../../../ui-react/src/service/APIService";

// create-react-app doesn't allow importing outside of the src folder (without some workarounds),
// but Angular doesn't have this restriction, so for staying DRY
// we put any shared classes in the react project and import it from Angular
// this is just to keep things simple and avoiding ejecting the create-react-app
// in the real world a separate package with the shared items should be considered

// set Amplify configuration
Amplify.configure(amplifyConfig);

interface Model {
  user?: User;
  errorMessage?: string;
  infoMessage?: string;
  pets: Pet[];
  selectedPet?: Pet;
  loading: boolean;
}

// @ts-ignore
/**
 * Our main component
 */
@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"],
  providers: [
    {
      provide: HttpAPIService,
      useFactory: () => new HttpAPIService(API, Auth),
    },
  ],
})
export class AppComponent implements OnInit {
  // ========================================================================
  // Public Members
  // ========================================================================

  model: Model = {
    user: undefined,
    errorMessage: undefined,
    infoMessage: undefined,
    pets: [],
    selectedPet: undefined,
    loading: false,
  };

  constructor(private apiService: HttpAPIService) {}

  // ========================================================================
  // Public methods
  // ========================================================================

  // ------------------------------------------------------------------------
  // Auth operations
  // ------------------------------------------------------------------------

  async ngOnInit(): Promise<void> {
    try {
      this.subscribeToAuthChanges();
      this.registerLoadingIndicator();
      await this.onLoad();
    } catch (e) {
      console.warn(e);
    }
  }

  async signIn(idpName?: string) {
    await Auth.federatedSignIn(
      idpName ? { customProvider: idpName } : undefined
    );
  }

  async signOut() {
    try {
      this.model.pets = [];
      this.model.user = undefined;
      await this.apiService.forceSignOut();
    } catch (e: any) {
      this.model.errorMessage = "Failed to sign out. " + e.message;
    }
  }

  // ------------------------------------------------------------------------
  // CRUD operations
  // ------------------------------------------------------------------------

  async getAllPets() {
    try {
      return await this.apiService.getAllPets();
    } catch (e: any) {
      console.warn(e);
      this.model.errorMessage = "Failed to get pets. " + e.message;
      return [];
    }
  }

  async savePet() {
    const pet = this.model.selectedPet;

    if (!pet) {
      this.model.errorMessage = "Pet is needed";
      return;
    }
    try {
      await this.apiService.savePet(pet);
      await this.loadAllPets();
    } catch (e: any) {
      this.model.errorMessage = "Failed to save pet. " + e.message;
    }
  }

  async deletePet() {
    if (!window.confirm("Are you sure?")) {
      return;
    }
    const pet = this.model.selectedPet;

    if (!pet) {
      this.model.errorMessage = "Pet is needed";
      return;
    }
    try {
      await this.apiService.deletePet(pet);
      await this.loadAllPets();
    } catch (e: any) {
      this.model.errorMessage = "Failed to delete pet. " + e.message;
    }
  }

  // ------------------------------------------------------------------------
  // Model operations
  // ------------------------------------------------------------------------

  newPet() {
    this.model.selectedPet = new Pet();
  }

  setSelectedPet(pet: Pet) {
    this.model.selectedPet = pet;
  }

  async loadAllPets() {
    this.model.pets = await this.getAllPets();
    this.model.selectedPet = undefined;
  }

  // ========================================================================
  // Private methods
  // ========================================================================

  private async onLoad() {
    const urlParams = new URLSearchParams(window.location.search);
    const idpParamName = "identity_provider";
    const idp = urlParams.get(idpParamName);

    try {
      this.model.user = await AppComponent.getUser();

      // remove identity_provider query param (not needed if signed in successfully)
      if (idp) {
        urlParams.delete(idpParamName);
        const params = urlParams.toString();
        window.history.replaceState(
          null,
          null as any,
          window.location.pathname + (params ? "?" + params : "")
        );
      }

      await this.loadAllPets();
    } catch (e) {
      if (e === "not authenticated" && idp) {
        await this.signIn(idp);
      }
    }
  }

  private static async getUser() {
    return new User(await Auth.currentAuthenticatedUser());
  }

  private subscribeToAuthChanges() {
    Hub.listen("auth", async ({ payload: { event, data } }) => {
      switch (event) {
        case "signIn":
        case "cognitoHostedUI":
          // workaround for FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
          // eslint-disable-next-line
          // noinspection SillyAssignmentJS
          window.location.hash = window.location.hash;
          await this.onLoad();

          break;
        case "signIn_failure":
        case "cognitoHostedUI_failure":
          this.model.user = undefined;
          console.warn(data);
          break;
        default:
          break;
      }
    });
  }

  private registerLoadingIndicator() {
    // show a loading indicator automatically
    Axios.interceptors.request.use(
      (config) => {
        this.model.loading = true;
        return config;
      },
      (error) => {
        this.model.loading = false;
        return Promise.reject(error);
      }
    );

    Axios.interceptors.response.use(
      (response) => {
        this.model.loading = false;
        return response;
      },
      (error) => {
        this.model.loading = false;
        return Promise.reject(error);
      }
    );
  }
}

<nav class="navbar navbar-expand-md navbar-dark bg-dark">

  <a class="navbar-brand" href="/">Amazon Cognito + AWS Amplify + Angular Demo</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
          aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>

    </ul>
    <ng-container *ngIf="model.user">
    <span *ngFor="let group of model.user.groups"
          class="badge badge-{{group.endsWith('admins') ? 'success' : 'info'}} mr-2">{{group}}</span>
    </ng-container>

    <div class="my-2 my-lg-0 navbar-nav">

      <ng-container *ngIf="model.user; else noUser">
        <div class="nav-item dropdown">
          <button class="nav-link dropdown-toggle btn btn-link" data-toggle="dropdown">{{model.user.name || model.user.email}}</button>
          <div class="dropdown-menu dropdown-menu-right">
            <button class="dropdown-item btn btn-warning" (click)="signOut()">Sign Out</button>
          </div>
        </div>
      </ng-container>
      <ng-template #noUser>
        <button class="btn btn-primary m-1" (click)="signIn('IdP')">Single Sign On</button>
        <button class="btn btn-primary m-1" (click)="signIn()">Sign In / Sign Up</button>
      </ng-template>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div *ngIf="model.errorMessage" (click)="model.errorMessage = undefined" class="alert alert-warning">{{model.errorMessage}}</div>
  <div *ngIf="model.infoMessage" (click)="model.infoMessage = undefined" class="alert alert-info">{{model.infoMessage}}</div>

  <div *ngIf="!model.user" class="alert alert-info">Please sign in</div>


  <div *ngIf="model.user" class="container">

    <table class="table">
      <thead>
      <tr>
        <th>owner</th>
        <th>type</th>
        <th>price</th>
      </tr>

      </thead>
      <tbody>
      <tr *ngFor="let pet of model.pets" id="row{{pet.id}}"
          (click)="setSelectedPet(pet)"
          class="{{model.selectedPet && pet.id === model.selectedPet.id ? 'table-active' : ''}}">
        <td><span class='badge badge-secondary'>{{pet.ownerDisplayName}}</span></td>
        <td><strong>{{pet.type}}</strong></td>
        <td>{{pet.price | currency}}</td>
      </tr>

      </tbody>
    </table>

    <ng-container *ngIf="model.selectedPet && model.selectedPet.id">
      <button class="btn btn-danger m-1" (click)="deletePet()">Delete</button>

    </ng-container>


    <button class="btn btn-primary m-1" (click)="newPet()">Create New</button>
    <button class="btn btn-success m-1" (click)="this.loadAllPets()">Reload</button>


    <div class="card" *ngIf="model.selectedPet">
      <div class="card-body">
        <form class="form-inline" (submit)="savePet()">
          <input class="form-control" type="hidden" [(ngModel)]="model.selectedPet.id" placeholder="Id" name="petId">
          <input class="form-control" type="text" [(ngModel)]="model.selectedPet.type" placeholder="Type" name="petType">
          <input class="form-control" type="text" [(ngModel)]="model.selectedPet.price" placeholder="Price" name="petPrice">
          <button type="submit" class="btn btn-success m-1">{{model.selectedPet.id ? "Update" : "Save"}}</button>
        </form>
      </div>
    </div>
    <div *ngIf="model.loading" class="d-flex justify-content-center">
      <div class="spinner-border" role="status">
        <span class="sr-only">Loading...</span>
      </div>
    </div>

  </div>

</div>

// ui-react/src/components/App.tsx
// App.js
import React, {ChangeEvent, Component, FormEvent, Fragment} from 'react';
import './App.css';
import {Auth, Hub} from 'aws-amplify';
import {CognitoUser} from '@aws-amplify/auth';
import {Pet} from "../model/pet";
import {User} from "../model/user";
import {APIService} from "../service/APIService";

const numberFormat = new Intl.NumberFormat(undefined, {
  style: 'currency',
  currency: 'USD',
  minimumFractionDigits: 0,
  maximumFractionDigits: 0
});

interface AppProps {
  apiService: APIService
}

export interface State {
  authState?: 'signedIn' | 'notSignedIn' | 'loading';
  user?: User;
  pets?: Pet[];
  error?: any;
  message?: string;
  selectedPet?: Pet;
  loading?: boolean;
}

class App extends Component<AppProps, State> {

  private apiService: APIService;

  constructor(props: AppProps) {

    super(props);

    this.apiService = props.apiService;

    this.state = {
      authState: 'loading',
    }
  }

  async componentDidMount() {
    console.log("componentDidMount");
    Hub.listen('auth', async ({payload: {event, data}}) => {
      switch (event) {
        case 'signIn':
        case 'cognitoHostedUI':
          let user = await this.getUser();
          // workaround for FF bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1422334
          // eslint-disable-next-line
          // noinspection SillyAssignmentJS
          window.location.hash = window.location.hash;
          this.setState({authState: 'signedIn', user: user});
          break;
        case 'signIn_failure':
        case 'cognitoHostedUI_failure':
          this.setState({authState: 'notSignedIn', user: null, error: data});
          break;
        default:
          break;
      }
    });

    try {
      let user = await this.getUser();
      this.setState({authState: 'signedIn', user: user});
    } catch (e) {
      console.warn(e);
      this.setState({authState: 'notSignedIn', user: null});
    }
  }

  private async getUser() {
    let cognitoUser: CognitoUser = await Auth.currentAuthenticatedUser();
    return new User(cognitoUser);
  }

  async componentDidUpdate(prevProps: Readonly<any>, prevState: Readonly<State>) {
    if (prevState.authState !== this.state.authState && this.state.authState === "signedIn") {
      await this.getAllPets();
    }
  }

  render() {

    const {authState, pets, user, error, selectedPet, message, loading}: Readonly<State> = this.state;

    let username: string;
    let groups: string[] = [];
    if(user) {
      // using first name for display
      username = user.name;
      groups = user.groups;
    }
    return (
      <Fragment>
        <nav className="navbar navbar-expand-md navbar-dark bg-dark">

          <a className="navbar-brand" href="/">Cognito + Amplify + React Demo</a>

          <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
                  aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"/>
          </button>


          <div className="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul className="navbar-nav mr-auto">
              <li className="nav-item active">
                <a className="nav-link" href="/">Home <span className="sr-only">(current)</span></a>
              </li>

            </ul>
            {[...groups].map(group =>
              <span className={`badge badge-${group.endsWith("admins") ? "success" : "info"} mr-2`}
                    key={group}>{group}</span>)}
            <div className="my-2 my-lg-0 navbar-nav">


              {authState === 'loading' && (<div>loading...</div>)}
              {authState === 'notSignedIn' &&
              <Fragment>
              <button className="btn btn-primary m-1" onClick={() => Auth.federatedSignIn({customProvider: "IdP"})}>Single Sign On</button>
              <button className="btn btn-primary m-1" onClick={() => Auth.federatedSignIn()}>Sign In / Sign Up</button>
              </Fragment>
              }
              {authState === 'signedIn' &&

              <div className="nav-item dropdown">
                <button className="nav-link dropdown-toggle btn btn-link" data-toggle="dropdown">{username}</button>
                <div className="dropdown-menu dropdown-menu-right">
                  <button className="dropdown-item btn btn-warning" onClick={() => this.signOut()}>Sign Out</button>
                </div>
              </div>
              }

            </div>
          </div>
        </nav>

        <div className="container-fluid">

          {error &&
          <div className="alert alert-warning" onClick={() => this.setState({error: null})}>{error.toString()}</div>}

          {message &&
          <div className="alert alert-info" onClick={() => this.setState({message: null})}>{message.toString()}</div>}

          {authState === 'notSignedIn' && <div className="alert alert-info">Please sign in</div>}

          {authState === 'signedIn' && <div className="container">
            {pets &&
            <table className="table">
              <thead>
              <tr>
                <th>owner</th>
                <th>type</th>
                <th>price</th>
              </tr>

              </thead>
              <tbody>
              {pets.map(pet =>
                <tr id={"row" + pet.id} key={pet.id}
                    onClick={() => this.setState({selectedPet: pet})}
                    className={selectedPet && pet.id === selectedPet.id ? "table-active" : ""}
                >
                  <td><span className='badge badge-secondary'>{pet.ownerDisplayName}</span></td>
                  <td><strong>{pet.type}</strong></td>
                  <td>{numberFormat.format(pet.price || 0)}</td>
                </tr>)
              }
              </tbody>
            </table>}


            {selectedPet && selectedPet.id &&
            <button className="btn btn-danger m-1" onClick={() => this.deletePet()}>Delete</button>}

            {<button className="btn btn-primary m-1" onClick={() => this.newOnClick()}>Create New</button>}

            {<button className="btn btn-success m-1" onClick={() => this.getAllPets()}>Reload</button>}


            {selectedPet &&
            <div className="card">
              <div className="card-body">
                <form className="form-inline" onSubmit={e => this.savePet(e)}>
                  <input className="form-control" type="hidden" value={selectedPet.id || ""} placeholder="Id"
                         onChange={e => this.handleChange(e, (state, value) => state.selectedPet.id = value)}/>
                  <input className="form-control" type="text" value={selectedPet.type || ""} placeholder="Type"
                         onChange={e => this.handleChange(e, (state, value) => state.selectedPet.type = value)}/>
                  <input className="form-control" type="text" value={selectedPet.price || ""} placeholder="Price"
                         onChange={e => this.handleChange(e, (state, value) => state.selectedPet.price = this.getAsNumber(value))}/>
                  <button type="submit" className="btn btn-success m-1">{selectedPet.id ? "Update" : "Save"}</button>

                </form>

              </div>
            </div>}


            {loading && <div className="d-flex justify-content-center">
              <div className="spinner-border" role="status">
                <span className="sr-only">Loading...</span>
              </div>
            </div>}


          </div>}

        </div>


      </Fragment>
    );
  }

  handleChange(event: ChangeEvent<HTMLInputElement>, mapper: (state: State, value: any) => void) {
    const value = event.target.value;
    this.setState(state => {
      mapper(state, value);
      return state;
    });
  }

  newOnClick() {
    // we explicitly set to null, undefined causes react to assume there was no change
    this.setState({selectedPet: new Pet()});

  }

  async getAllPets() {
    try {
      this.setState({loading: true, selectedPet: undefined});
      let pets: Pet[] = await this.apiService.getAllPets();
      this.setState({pets, loading: false});
    } catch (e) {
      console.log(e);
      this.setState({error: `Failed to load pets: ${e}`, pets: [], loading: false});
    }
  }

  async savePet(event: FormEvent<HTMLFormElement>) {

    event.preventDefault();


    const pet = this.state.selectedPet;

    if (!pet) {
      this.setState({error: "Pet is needed"});
      return;
    }
    try {
      this.setState({loading: true});
      await this.apiService.savePet(pet);

      await this.getAllPets();
    } catch (e) {
      this.setState({error: "Failed to save pet. " + e.message, loading: false});
    }
  }

  async deletePet() {

    if (!window.confirm("Are you sure?")) {
      return;
    }
    const pet = this.state.selectedPet;

    if (!pet) {
      this.setState({error: "Pet is needed"});
      return;
    }
    try {
      this.setState({loading: true});
      await this.apiService.deletePet(pet);
      return this.getAllPets();
    } catch (e) {
      this.setState({error: "Failed to save pet. " + e.message, loading: false});
    }
  }

  async signOut() {
    try {
      this.setState({authState: 'notSignedIn', pets: null, user: null});
      await this.apiService.forceSignOut();
    } catch (e) {
      console.log(e);
    }
  }

  private getAsNumber(value: any): number | undefined {
    if (value) {
      try {
        return parseInt(value)
      } catch (ignored) {
      }
    }
    return undefined;
  }
}

export default App;
